name: vvc-drl-env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - cyipopt        # optional nonlinear solver, if used
  - pip:
    - gymnasium
    - stable-baselines3
    - pandapower
    - torch>=1.12,<2.0    # CPU version; for GPU replace with appropriate cudatoolkit build
    - cvxpy
    - tensorboard         # for logging
    - tqdm                # CLI progress bars
